name: Run Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build tests
      run: |
        mkdir cmake-build-test
        cd cmake-build-test
        cmake .. -DNULLSAFETY_BUILD_TESTS=true
        make
    - name: run tests
      run: |
        cd cmake-build-test
        ./tests/null-safety-tests -s
      timeout-minutes: 5